name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: |
        cd /home/runner/work/hello-world/hello-world" 
        zip -r hello-world.zip . -x ".git/*" ".github/*"

      - name: Congiguring jFrog CLI...
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_ADVANCEDCSG }}

      - name: publishing to jfrog artifactory...
        run: |
          jfrog rt u hello-world.zip cloudformation-local/advanced/edu-ops-new/api/hello-world.zip